device: cpu

data:
    data_dir: 
    global_batch_size: 16
    shuffle: True
    n_epochs: 128
    prefetch: 4
  
opt:
    name: Lamb
    betas: [0.9, 0.999]
    weight_decay: 0.01
  
lr_schedule:
    type: poly
    base_lr: 0.00005
    total_steps: 0
    lr_warmup_steps: 0
    start_warmup_step: 0

training:
    target_mlm_accuracy: 0.72
