device: cpu

data:
    data_dir: /work/z043/z043/shared/imagenet-1k/huggingface/data
    global_batch_size: 256
    drop_last_batch: True
    shuffle: True
    n_epochs: 128
    prefetch: 4

opt:
    name: SGD
    momentum: 0.9
    weight_decay: 0.0001

lr_schedule:
    base_lr: 0.002
    end_lr: 0.0001
    decay_steps: 5
    poly_power: 2 
