device: cpu

data:
    global_batch_size: 1
    local_batch_size: 0 # change to 0 to use global_batch_size
    train_subset: 0
    val_subset: 0
    gradient_accumulation_freq: -1  # -1 will automatically determine the best frequency for a 128 core cpu
    drop_last_batch: True
    shuffle: True
    n_epochs: 4
    prefetch: 4

opt:
    name: Adam
    betas: [0.9, 0.999]
    weight_decay: 0.0001

lr_schedule:
    type: cosine_annealing # or multistep
    #for both cos & mul
    base_lr: 0.001
    lr_warmup_steps: 400
    lr_warmup_factor: 1
    #mul
    milestones: 800
    decay_rate: 0.1
    #cos
    t_max: 10000
    eta_min: 0

training:
    target_iou: 0.82
    num_ipus: 1
