device: cpu

data:
    data_dir: /path/to/data
    n_epochs: 128
    global_batch_size: 4096
    gradient_accumulation: 4

opt:
    name: ADAM
    betas: [0.9, 0.95]
    weight_decay: 0.1
    gradient_clip_norm: 1.0
    
lr_schedule:
    base_lr: 0.00002

parallelism:
    tp_size: 4
    pp_size: 2
    precision: fp16
    zero_stage: 1
    cpu_offload: False  # can only be true if device is gpu/cuda 