train_input:
    data_dir: "/home/z043/z043/crae-cs1/data/cosmoUniverse_2019_05_4parE_tf_v2_mini/train"
    batch_size: 128
    drop_last_batch: True
    shuffle: True

eval_input:
    data_dir: "/home/z043/z043/crae-cs1/data/cosmoUniverse_2019_05_4parE_tf_v2_mini/validation"
    batch_size: 128
    drop_last_batch: True

model:
    name: "CosmoFlow"
    mixed_precision: True

optimizer:
    optimizer_type: "SGD"
    learning_rate: 0.001
    momentum: 0.9
    weight_decay_rate: 0.0001

runconfig:
    max_steps: 10000
    checkpoint_steps: 2000
    log_steps: 50
    seed: 333
    save_losses: True