train_input:
    data_dir: "data/train"
    batch_size: 64
    drop_last_batch: True
    shuffle: True
    to_float16: True

eval_input:
    data_dir: "data/val"
    batch_size: 32
    drop_last_batch: True
    to_float16: True

model:
    name: "ResNet50"
    mixed_precision: True

optimizer:
    optimizer_type: "SGD"
    learning_rate: 0.001
    momentum: 0.9
    weight_decay_rate: 0.0001

runconfig:
    max_steps: 10000
    checkpoint_steps: 10000
    log_steps: 50
    seed: 1
    save_losses: True
